pipeline:
  compile and tests:
    image: edouardlopez/docker-criterion:latest
    commands:
      - mkdir build
      - gcc -I include -o build/out testcase/test.c src/*.c -lcriterion
      - build/out --pattern execise/${TESTRANGE}

matrix:
  TESTRANGE: [ 1, 2, 3 ]

guide:
  name: C test
  desc: >
    Example project to demonstrate unit testing C
    code
  labels:
    - C
