pipeline:
  compile and tests:
    image: edouardlopez/docker-criterion:latest
    commands:
      - mkdir build
      - gcc -o build/out work/sample.c -lcriterion
      - build/out

# matrix:
#   TESTRANGE: [ 1, 2 ]

guide:
  name: C test
  desc: >
    Example project to demonstrate unit testing C
    code
  labels:
    - C
